### PR TITLE
Fix memory leak due to focus listeners not being deleted

### LINKED ISSUE #142: bug: slow down & memory leak due to undetached event listeners
Steps to reproduce

1. Go to a webpage which has DOM mutations
2. Import and start the virtual screen reader
    ```
    const { virtual } = await import('https://unpkg.com/@guidepup/virtual-screen-reader/lib/esm/index.browser.js');
    await virtual.start({ container: document.body });
    ```
3. Do some things to trigger DOM mutations
4. Notice that elements begin to have many identical focus event listeners
    
Image

### PR DESCRIPTION
**Pull request by ysgit**
# Issue

Fixes #142 

## Details

This replaces the current implementation for focus management that uses a focus event listener on each node in the accessibility tree with a focusin event listener that sits at the container level.

## CheckList

- [X] Ensured all current tests are passing

### CODE REVIEW

File: src/Virtual.ts [hunk 1]
```diff
@@ -290,28 +288,9 @@ export class Virtual {
...
-  }
-
-  #detachFocusListeners() {
-    this.#getAccessibilityTree().forEach((treeNode) => {
-      treeNode.node.removeEventListener(
-        "focus",
-        this.#handleFocusChange.bind(this)
-      );
-    });
-  }
```
Comment (jlp-craigmorten) [inline src/Virtual.ts:313]: Hmm, guess the detach logic was flawed!

File: src/Virtual.ts [hunk 2]
```diff
@@ -322,10 +301,13 @@ export class Virtual {
...
-    // index or we default back to the beginning of the tree.
-    const newActiveNode =
-      tree.find(({ node }) => node === target) ?? tree.at(0)!;
+    // We've covered the tree having no length so there should be at least one
+    // matching node, but if not we will not update the state
+    const newActiveNode = tree.find(({ node }) => node === target);
+
+    if (!newActiveNode) {
+      return;
+    }
```
Comment (jlp-craigmorten) [inline src/Virtual.ts:310]: Unsure about changing the logic here... be interested to understand your thoughts?

I _think_ my reasoning was that focusing an element that isn't in the tree is considered somewhat lost focus, so the virtual cursor get's placed on the container (the equivalent of the body if working against the entire page).

Perhaps need to fact check what NVDA, VO, actually do in this scenario to compare. Though, there's no requirement for this lib to mirror them exactly so more relevant to follow anything regarding focus management in the specs (which I don't think there is anything).

I guess this change has the potential to trigger focus events for a superset of what we had before as the `focusin` applies to the entire container opposed to just nodes in the tree itself... might be frustrating for the cursor to jump to the container every time something outside the tree gains focus? Unsure!

File: src/Virtual.ts [hunk 3]
```diff
@@ -619,6 +601,8 @@ export class Virtual {
       return;
     }
 
+    this.#container.addEventListener("focusin", this.#handleFocusChange.bind(this));
```
Comment (jlp-craigmorten) [inline src/Virtual.ts:604]: Mirroring the original issue (but to a lesser extent), let's add a `removeEventListener` to the `.stop()` method so we don't have a lesser memory leak there!

Comment (ysgit) [reply src/Virtual.ts]: Thanks for the feedback, I've added this

File: src/Virtual.ts (hunk 2 above)
Comment (ysgit) [reply src/Virtual.ts:311]: This is a tricky one.

Originally I didn't change this logic and it broke some of the `ariaLive` tests. For instance [this test](https://github.com/guidepup/virtual-screen-reader/blob/4cd3fa36cbd83726df1395daadb13cf39b416d8c/test/int/ariaLive.int.test.ts#L42).

What happened is that the spoke phrase log became
```
      "document",
      "button, Test aria-live polite",
      "document",
      "polite: Existing Content",
      "polite: Existing Content u"
```

The reason appears to be that the contenteditable divs are not in the accessibility tree - maybe because they don't have a role? They become focused when you do `userEvent.click()`.

I could modify the test to give them a role but then there's a wider question. Shouldn't everything in the focus sequence be in the accessibility tree? If I understand correctly, that's why you can't use `aria-hidden` on something in the focus sequence.

Another situation where this could occur is on a nested interactive. In that scenario I think the right thing would be to keep the screen reader cursor on the parent interactive.

Comment (jlp-craigmorten) [reply src/Virtual.ts:311]: Hmm, interesting!

In the test case you've shared the contenteditible div have an implicit `generic` role which does allow for `aria-live` so the live region support is correct. What this lib hasn't done to date is consider whether something being focusable should result in it's inclusion in the tree, currently all `generic` elements are ignored and effectively replaced by their children... perhaps there are cases where that shouldn't happen 🤔

Comment (cmorten) [reply src/Virtual.ts:311]: Let’s take this away and handle separately - your changes appear to have passed current test suite so feels like a positive change to get in and iterate on
